### ISSUE TITLE
error when build mit-scheme-kernel

### ISSUE THREAD

**Issue by hlyang1992** [joeltg/mit-scheme-kernel#18]
Hi,

I successfully installed  Mit Scheme and  ZeroMQ. When I build mit-scheme-kernel,  I get the following error information.  My system is MacOS 10.15.4.

```
echo '(generate-shim "zmq" "#include <zmq.h>")' | /usr/local/bin/mit-scheme --batch-mode
;Including zmq.cdecl... done
;Generating "zmq-shim.c"...
;Warning: Unknown type: zmq_timer_fn
;... done
;Generating "zmq-const.c"... done
;Dumping "zmq-types.bin"... done
cc -I/usr/local/lib/mit-scheme-x86-64 -Wall  -fPIC `pkg-config --cflags libzmq` -o zmq-shim.o -c zmq-shim.c
cc -shared -fPIC  -o zmq-shim.so zmq-shim.o `pkg-config --libs libzmq`
Undefined symbols for architecture x86_64:
  "_arg_long", referenced from:
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      _Scm_zmq_getsockopt in zmq-shim.o
      _Scm_zmq_msg_get in zmq-shim.o
      _Scm_zmq_msg_init_data in zmq-shim.o
      _Scm_zmq_msg_recv in zmq-shim.o
      _Scm_zmq_msg_send in zmq-shim.o
      ...
  "_arg_pointer", referenced from:
      _Scm_zmq_bind in zmq-shim.o
      _Scm_zmq_close in zmq-shim.o
      _Scm_zmq_connect in zmq-shim.o
      _Scm_zmq_ctx_destroy in zmq-shim.o
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      _Scm_zmq_ctx_shutdown in zmq-shim.o
      ...
  "_arg_ulong", referenced from:
      _Scm_zmq_msg_init_data in zmq-shim.o
      _Scm_zmq_msg_init_size in zmq-shim.o
      _Scm_zmq_recv in zmq-shim.o
      _Scm_zmq_send_const in zmq-shim.o
      _Scm_zmq_send in zmq-shim.o
      _Scm_zmq_setsockopt in zmq-shim.o
      _Scm_zmq_timers_set_interval in zmq-shim.o
      ...
  "_callback_lunseal", referenced from:
      _Scm_kernel_zmq_free_fn in zmq-shim.o
      _Scm_kernel_zmq_timer_fn in zmq-shim.o
  "_callback_return", referenced from:
      _Scm_kernel_zmq_free_fn in zmq-shim.o
      _Scm_kernel_zmq_timer_fn in zmq-shim.o
  "_callback_run_handler", referenced from:
      _Scm_kernel_zmq_free_fn in zmq-shim.o
      _Scm_kernel_zmq_timer_fn in zmq-shim.o
  "_callback_run_kernel", referenced from:
      _Scm_zmq_free_fn in zmq-shim.o
      _Scm_zmq_timer_fn in zmq-shim.o
  "_callout_continue", referenced from:
      _Scm_zmq_bind in zmq-shim.o
      _Scm_zmq_close in zmq-shim.o
      _Scm_zmq_connect in zmq-shim.o
      _Scm_zmq_ctx_destroy in zmq-shim.o
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_new in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      ...
  "_callout_lunseal", referenced from:
      _Scm_continue_zmq_bind in zmq-shim.o
      _Scm_continue_zmq_close in zmq-shim.o
      _Scm_continue_zmq_connect in zmq-shim.o
      _Scm_continue_zmq_ctx_destroy in zmq-shim.o
      _Scm_continue_zmq_ctx_get in zmq-shim.o
      _Scm_continue_zmq_ctx_new in zmq-shim.o
      _Scm_continue_zmq_ctx_set in zmq-shim.o
      ...
  "_callout_pop", referenced from:
      _Scm_continue_zmq_bind in zmq-shim.o
      _Scm_continue_zmq_close in zmq-shim.o
      _Scm_continue_zmq_connect in zmq-shim.o
      _Scm_continue_zmq_ctx_destroy in zmq-shim.o
      _Scm_continue_zmq_ctx_get in zmq-shim.o
      _Scm_continue_zmq_ctx_new in zmq-shim.o
      _Scm_continue_zmq_ctx_set in zmq-shim.o
      ...
  "_callout_seal", referenced from:
      _Scm_zmq_bind in zmq-shim.o
      _Scm_zmq_close in zmq-shim.o
      _Scm_zmq_connect in zmq-shim.o
      _Scm_zmq_ctx_destroy in zmq-shim.o
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_new in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      ...
  "_callout_unseal", referenced from:
      _Scm_zmq_bind in zmq-shim.o
      _Scm_zmq_close in zmq-shim.o
      _Scm_zmq_connect in zmq-shim.o
      _Scm_zmq_ctx_destroy in zmq-shim.o
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_new in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      ...
  "_check_number_of_args", referenced from:
      _Scm_zmq_bind in zmq-shim.o
      _Scm_zmq_close in zmq-shim.o
      _Scm_zmq_connect in zmq-shim.o
      _Scm_zmq_ctx_destroy in zmq-shim.o
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_new in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      ...
  "_cons", referenced from:
      _Scm_kernel_zmq_free_fn in zmq-shim.o
      _Scm_kernel_zmq_timer_fn in zmq-shim.o
     (maybe you meant: _Scm_zmq_send_const, _Scm_continue_zmq_send_const )
  "_cons_alien", referenced from:
      _Scm_kernel_zmq_free_fn in zmq-shim.o
  "_cstack_lpop", referenced from:
      _Scm_continue_zmq_bind in zmq-shim.o
      _Scm_continue_zmq_close in zmq-shim.o
      _Scm_continue_zmq_connect in zmq-shim.o
      _Scm_continue_zmq_ctx_destroy in zmq-shim.o
      _Scm_continue_zmq_ctx_get in zmq-shim.o
      _Scm_continue_zmq_ctx_new in zmq-shim.o
      _Scm_continue_zmq_ctx_set in zmq-shim.o
      ...
  "_cstack_push", referenced from:
      _Scm_zmq_bind in zmq-shim.o
      _Scm_zmq_close in zmq-shim.o
      _Scm_zmq_connect in zmq-shim.o
      _Scm_zmq_ctx_destroy in zmq-shim.o
      _Scm_zmq_ctx_get in zmq-shim.o
      _Scm_zmq_ctx_new in zmq-shim.o
      _Scm_zmq_ctx_set in zmq-shim.o
      ...
  "_empty_list", referenced from:
      _Scm_kernel_zmq_free_fn in zmq-shim.o
      _Scm_kernel_zmq_timer_fn in zmq-shim.o
  "_long_to_scm", referenced from:
      _Scm_continue_zmq_bind in zmq-shim.o
      _Scm_continue_zmq_close in zmq-shim.o
      _Scm_continue_zmq_connect in zmq-shim.o
      _Scm_continue_zmq_ctx_destroy in zmq-shim.o
      _Scm_continue_zmq_ctx_get in zmq-shim.o
      _Scm_continue_zmq_ctx_set in zmq-shim.o
      _Scm_continue_zmq_ctx_shutdown in zmq-shim.o
      ...
  "_pointer_to_scm", referenced from:
      _Scm_continue_zmq_ctx_new in zmq-shim.o
      _Scm_continue_zmq_msg_data in zmq-shim.o
      _Scm_continue_zmq_msg_gets in zmq-shim.o
      _Scm_continue_zmq_socket in zmq-shim.o
      _Scm_continue_zmq_strerror in zmq-shim.o
      _Scm_continue_zmq_timers_new in zmq-shim.o
      _Scm_continue_zmq_z85_decode in zmq-shim.o
      ...
  "_ulong_to_scm", referenced from:
      _Scm_continue_zmq_msg_size in zmq-shim.o
  "_unspecific", referenced from:
      _Scm_continue_zmq_version in zmq-shim.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [zmq-shim.so] Error 1

```

**Comment by joeltg** [comment]
Have you tried installing `pkg-config` from brew and adding a `-undefined dynamic_lookup` flag to the makefile in the line that builds zmq-shim.so?

So that the line looks like
```
$(CC) -shared -fPIC -undefined dynamic_lookup -o $@ $^ `pkg-config --libs libzmq`
```

instead of
```
$(CC) -shared -fPIC -o $@ $^ `pkg-config --libs libzmq`
```

(This was mentioned in the readme but it's not very prominent. I should be able to detect this automatically, but haven't had the energy yet.)

**Comment by hlyang1992** [comment]
Thank you very much. I forget add flag `-undefined dynamic_lookup`.

**Comment by hlyang1992** [comment]
But when I create new notebook, I got the `kernel error`. The error information is as follow:

```
Traceback (most recent call last):
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/jupyter_client/manager.py", line 305, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/jupyter_client/manager.py", line 212, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 135, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/hlyang/Root/opt/py3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scheme': 'scheme'
```
